import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const { searchParams } = new URL(req.url)
  const sellingPrice = searchParams.get('selling_price')
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? process.env.API_URL ?? 'http://localhost:3001'

  // Fetch listing and closing costs
  const [listingRes, costsRes] = await Promise.all([
    fetch(`${apiUrl}/listings/${params.id}`),
    fetch(`${apiUrl}/listings/${params.id}/closing-costs${sellingPrice ? `?selling_price=${sellingPrice}` : ''}`),
  ])

  const listing = await listingRes.json()
  const costs = await costsRes.json()

  // Generate simple HTML-based PDF content
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Total Cost of Investment</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #1a1a1a; }
    h1 { color: #2563eb; font-size: 20px; margin-bottom: 4px; }
    .subtitle { color: #6b7280; font-size: 12px; margin-bottom: 24px; }
    .property-box { background: #f3f4f6; border-radius: 8px; padding: 16px; margin-bottom: 24px; }
    .property-box h2 { font-size: 16px; margin: 0 0 8px; }
    .property-box p { font-size: 12px; color: #6b7280; margin: 2px 0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { text-align: left; font-size: 11px; color: #6b7280; padding: 6px 0; border-bottom: 1px solid #e5e7eb; }
    td { font-size: 13px; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
    td:last-child { text-align: right; font-weight: 500; }
    .total-row td { font-weight: bold; font-size: 14px; border-top: 2px solid #2563eb; color: #2563eb; }
    .grand-total td { font-weight: bold; font-size: 16px; color: #059669; }
    .disclaimer { font-size: 10px; color: #9ca3af; margin-top: 24px; line-height: 1.5; }
    .watermark { font-size: 10px; color: #d1d5db; text-align: center; margin-top: 40px; }
  </style>
</head>
<body>
  <h1>Total Cost of Investment</h1>
  <p class="subtitle">Generated by OFW Realty Marketplace · ${new Date().toLocaleDateString('en-PH', { dateStyle: 'long' })}</p>

  <div class="property-box">
    <h2>${listing.title ?? 'Property'}</h2>
    <p>${listing.property_type?.replace('_', ' ')} · ${listing.city ?? ''}, ${listing.province ?? ''}</p>
    <p>Selling Price: ₱${Number(costs.selling_price).toLocaleString()}</p>
  </div>

  <table>
    <tr><th>Fee</th><th style="text-align:right">Amount (PHP)</th></tr>
    <tr><td>Selling Price</td><td>₱${Number(costs.selling_price).toLocaleString()}</td></tr>
    <tr><td>Capital Gains Tax (6%)</td><td>₱${Number(costs.breakdown.cgt).toLocaleString()}</td></tr>
    <tr><td>Documentary Stamp Tax (1.5%)</td><td>₱${Number(costs.breakdown.dst).toLocaleString()}</td></tr>
    <tr><td>Transfer Tax (LGU rate)</td><td>₱${Number(costs.breakdown.transfer_tax).toLocaleString()}</td></tr>
    <tr><td>Registration Fee (LRA)</td><td>₱${Number(costs.breakdown.registration_fee).toLocaleString()}</td></tr>
    <tr><td>Notarial Fee</td><td>₱${Number(costs.breakdown.notarial_fee).toLocaleString()}</td></tr>
    <tr><td>Miscellaneous Fees</td><td>₱${Number(costs.breakdown.misc_fees).toLocaleString()}</td></tr>
    <tr class="total-row"><td>Total Closing Costs</td><td>₱${Number(costs.total).toLocaleString()}</td></tr>
    <tr class="grand-total"><td>TOTAL INVESTMENT</td><td>₱${(Number(costs.selling_price) + Number(costs.total)).toLocaleString()}</td></tr>
  </table>

  <p class="disclaimer">${costs.disclaimer}</p>
  <p class="watermark">Generated by OFW Realty Marketplace — Not for redistribution · ${listing.title ?? ''} · ${new Date().toISOString()}</p>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="total-cost-of-investment-${params.id}.html"`,
    },
  })
}
